name: AppMercadoVirtual
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State manager
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  
  #permission to camera
  permission_handler: ^5.0.1+1

  #unity
  flutter_unity_widget: ^0.1.6+5

  #QR code scan
  flutter_qr_reader: ^1.0.3

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  provider: ^3.1.1
  lite_rolling_switch: ^0.1.1
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.1.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/proxima-nova.otf

  assets:
    - assets/products/
    - assets/logo/
    - assets/
